spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoga?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.woniuxy.pojo




  